### PR TITLE
Set user's email_verified_at after setting password

### LINKED ISSUE #3: Email not marked as verified after setting password
My assumption was that the user would have `email_verified_at` set once they've set their password. Since they use the link in the email, they're as good as verified at that point. I'd also like to piggy-back off that field to know when the user accepted the invite and joined.

Should this be done in `handleAfterRedirect` of the middleware? Seems like the right place to put it, since the current user should be known at that point.

### PR DESCRIPTION
**Pull request by francislavoie**
Fixes #3

Took a crack at implementing it, seems to work for my situation. I didn't write any tests though, would probably be best to do so. The logic is mostly taken from the `MustVerifyEmail` trait built into the Laravel auth.

### CODE REVIEW

**Comment by tontonsb** [comment]
I think this should work pretty much the same as the original verification in the following senses:
- do nothing if already verified;
- use the method defined in the interface instead of manually setting a column;
- fire an event.

I did a little edit to your PR making the above changes. Let me know if I introduced something undesirable. If not, I will merge this soon.

**Comment by francislavoie** [comment]
I added a missing `use` for the event you added.

LGTM! I didn't think of doing it that way, much cleaner.

**Comment by francislavoie** [comment]
@tontonsb could you tag a release?

**Comment by tontonsb** [comment]
@francislavoie done!

**Comment by francislavoie** [comment]
Thank you!

**Pull request merged**
